@startuml
'https://plantuml.com/sequence-diagram

autonumber



InitImp -> InitAsyncRunnable: execute InitAsyncRunnable
InitAsyncRunnable -> InitAsyncRunnable :initUtil
InitAsyncRunnable -> AdapterUtil :initAdapter
AdapterUtil -> AdapterUtil :createAdapter 反射调用
AdapterUtil -> AdapterUtil :存储到SparseArray<CustomAdsAdapter> mAdapter容器中


@enduml