@startuml
'https://plantuml.com/sequence-diagram

autonumber

媒体APP -> OmAds: init(configuration,callback)
OmAds -> OmManager: init(configuration,callback)
OmManager -> OmManager:判断初始化状态
OmManager --> 媒体APP: 已初始化: onSuccess
OmManager ->OmManager: 正在初始化: addCallback
OmManager -> InitImp:未初始化: init(configuration)
InitImp -> InitImp: saveInitConfig
InitImp -> InitImp: getGaid/getOaid
InitImp->ConfigurationHelper: initUtil 初始化AdapterUtil,DataCache
InitImp->ConfigurationHelper: getConfiguration(appkey,initHost)\n 获取云侧配置信息
ConfigurationHelper -->InitImp:onRequestSuccess(response)\n 返回配置信息
InitImp -> ConfigurationHelper: parseFormServerResponse\n 解析配置信息
InitImp -> InitImp: saveInitData\n 缓存配置信息
InitImp -> InitImp: start InitScheduleTask 启动定时任务，间隔n分钟初重新获取配置信息
InitImp --> OmManager:onSuccess
OmManager -> OmManager:a.初始化Manager\nb,设置各类型广告监听器\nc,检查各类型广告加载任务队列\nd，预加载广告
OmManager -->媒体APP: init onSuccess
@enduml