@startuml
'https://plantuml.com/sequence-diagram

autonumber

媒体APP -> OmAds: init(configuration,callback)
OmAds -> OmManager: init(configuration,callback)
OmManager -> OmManager:初始化成功回调onSuccess，\n或者已经初始化anotherInitCalledAfterInitSuccess
OmManager -> OmManager:根据AD_TYPE 预加载指定类型的广告。\n当前支持的有REWARDED,INTERSTITIAL,PROMOTION广告支持预加载
OmManager ->AbstractAdsApi: loadAds 请求加载广告
@enduml